### ISSUE TITLE
be deploy failure to b3lvs0506

### ISSUE THREAD

**Issue by joshbynon-bp** [bulletproofnetworks/ript#21]
I am encountering this issue. Hopefully its not my environment causing this but it appears to be the other side of the fence?

```
be cap b3lvs0506 deploy HOSTFILTER=bp-pmdh-b3lvs-05.inf.bulletproof.net
  * executing `b3lvs0506'
    triggering start callbacks for `deploy'
  * executing `multistage:ensure'
  * executing `deploy'
  * executing `deploy:update'
 ** transaction: start
  * executing `deploy:update_code'
    executing locally: "git ls-remote git@github.com:bulletproofnetworks/ript-rules.git HEAD"
  * executing "git clone -q git@github.com:bulletproofnetworks/ript-rules.git /etc/firewall/releases/20151029115703 && cd /etc/firewall/releases/20151029115703 && git checkout -q -b deploy 17ea66418946d32d8e0b587bedfe1d4c54872c37 && (echo 17ea66418946d32d8e0b587bedfe1d4c54872c37 > /etc/firewall/releases/20151029115703/REVISION)"
    servers: ["bp-pmdh-b3lvs-05.inf.bulletproof.net"]
    [bp-pmdh-b3lvs-05.inf.bulletproof.net] executing command
    command finished in 7191ms
  * executing `deploy:finalize_update'
  * executing "chmod -R g+w /etc/firewall/releases/20151029115703"
    servers: ["bp-pmdh-b3lvs-05.inf.bulletproof.net"]
    [bp-pmdh-b3lvs-05.inf.bulletproof.net] executing command
    command finished in 143ms
  * executing `deploy:symlink'
  * executing "rm -f /etc/firewall/current && ln -s /etc/firewall/releases/20151029115703 /etc/firewall/current"
    servers: ["bp-pmdh-b3lvs-05.inf.bulletproof.net"]
    [bp-pmdh-b3lvs-05.inf.bulletproof.net] executing command
    command finished in 108ms
 ** transaction: commit
    triggering after callbacks for `deploy'
  * executing `deploy:post'
Diff the rules
  * executing "sudo -p 'sudo password: ' rbenv-exec ript rules diff /etc/firewall/current/firewalls/b3lvs0506/customers"
    servers: ["bp-pmdh-b3lvs-05.inf.bulletproof.net"]
    [bp-pmdh-b3lvs-05.inf.bulletproof.net] executing command
Password:
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net]
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] Looks like you found a bug in Ript around line 9 in /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/lib/ript/dsl/primitives/nat.rb
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] Specifically, this is the exception raised:
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net]
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] undefined method `[]' for nil:NilClass
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net]
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] And here is the backtrace:
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net]
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/lib/ript/dsl/primitives/nat.rb:98:in `block (4 levels) in rewrite'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/lib/ript/dsl/primitives/nat.rb:98:in `map'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/lib/ript/dsl/primitives/nat.rb:98:in `block (3 levels) in rewrite'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/lib/ript/dsl/primitives/nat.rb:97:in `each'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/lib/ript/dsl/primitives/nat.rb:97:in `block (2 levels) in rewrite'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/lib/ript/dsl/primitives/nat.rb:96:in `each'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/lib/ript/dsl/primitives/nat.rb:96:in `block in rewrite'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/lib/ript/dsl/primitives/nat.rb:75:in `each'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/lib/ript/dsl/primitives/nat.rb:75:in `rewrite'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /etc/firewall/current/firewalls/b3lvs0506/customers/intershop.rb:34:in `block in <top (required)>'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/lib/ript/partition.rb:39:in `instance_eval'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/lib/ript/partition.rb:39:in `initialize'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/lib/ript/partition.rb:160:in `new'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/lib/ript/partition.rb:160:in `partition'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /etc/firewall/current/firewalls/b3lvs0506/customers/intershop.rb:1:in `<top (required)>'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net]
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:53:in `require'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/bin/ript:81:in `block in <top (required)>'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net]
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/bin/ript:80:in `each'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/lib/ruby/gems/1.9.1/gems/ript-0.8.7/bin/ript:80:in `<top (required)>'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net]
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/bin/ript:23:in `load'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] /opt/rbenv/versions/1.9.2-p290/bin/ript:23:in `<main>'
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net]
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] Please report this bug at http://github.com/bulletproofnetworks/ript
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net]
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net]
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net] Aborting.
 ** [out :: bp-pmdh-b3lvs-05.inf.bulletproof.net]
    command finished in 2494ms
failed: "env RBENV_ROOT=/opt/rbenv PATH=/opt/rbenv/bin/:$PATH /bin/bash -c 'sudo -p '\\''sudo password: '\\'' rbenv-exec ript rules diff /etc/firewall/current/firewalls/b3lvs0506/customers'" on bp-pmdh-b3lvs-05.inf.bulletproof.net
```

**Comment by nerdyness** [comment]
Hi @joshbynon-bp, check out [this line](https://github.com/bulletproofnetworks/ript-rules/commit/17ea66418946d32d8e0b587bedfe1d4c54872c37#diff-e4de6ac95a1d47afdbd733607b0754a7R36) in your commit.

It should read `from "intershop temp", 
intershop temp 2", "intershop temp 3"`.

Let me know (re-open) if you've got any further trouble with this :+1:

**Comment by joshbynon-bp** [comment]
Hi @nerdyness,

Appreciate that! silly me.

@davidmckenzie you approved this <g>
